#!/usr/bin/env bash

# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
# Configure localhost to resolve to 127.0.0.2
# sed -i s/^127.0.0.2/127.0.0.1/ ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
# Configure facebook.com to resolve to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
