#!/usr/bin/env bash
# Generating SSH key-pairs according to Task requirements

read -sp "Enter passphrase for the RSA key: " passphrase
echo

ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "$passphrase"

echo "RSA key pair created successfully."
